#      ______                ____                 __
#     / ____/   _____  _____/ __ )____  _________/ /__  _____
#    / __/ | | / / _ \/ ___/ __  / __ \/ ___/ __  / _ \/ ___/
#   / /___ | |/ /  __/ /  / /_/ / /_/ / /  / /_/ /  __/ /
#  /_____/ |___/\___/_/  /_____/\____/_/   \__,_/\___/_/
#
# EverBorder Plugin, made with ♥ by UnStackss
# UnStackss GitHub: https://github.com/EverCraftTeam
# For support join the discord server: https://discord.evercraft.it

# Metrics (https://bstats.org/plugin/bukkit/EverGens/23477)
bStats: true
